# Generated by Django 5.2.4 on 2025-07-26 15:44

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFeatures',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('asset_url', models.URLField(blank=True, db_index=True, max_length=1024, null=True)),
                ('source_page_url', models.URLField(db_index=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioFeatures',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('asset_url', models.URLField(blank=True, db_index=True, max_length=1024, null=True)),
                ('source_page_url', models.URLField(db_index=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('begin_stamp_seconds', models.PositiveIntegerField()),
                ('end_stamp_seconds', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset_url', 'begin_stamp_seconds'), name='unique_audio_chunk')],
            },
        ),
        migrations.CreateModel(
            name='ImageFeatures',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('asset_url', models.URLField(blank=True, db_index=True, max_length=1024, null=True)),
                ('source_page_url', models.URLField(db_index=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alt_text', models.CharField(blank=True, max_length=512)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset_url',), name='unique_image_asset_url')],
            },
        ),
    ]
