# Generated by Django 5.2.4 on 2025-09-01 07:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_url', models.URLField(blank=True, db_index=True, max_length=1024, null=True)),
                ('source_page_url', models.URLField(db_index=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('begin_stamp_seconds', models.PositiveIntegerField()),
                ('end_stamp_seconds', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset_url', 'begin_stamp_seconds'), name='unique_audio_chunk')],
            },
        ),
        migrations.CreateModel(
            name='ImageFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_url', models.URLField(blank=True, db_index=True, max_length=1024, null=True)),
                ('source_page_url', models.URLField(db_index=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alt_text', models.CharField(blank=True, max_length=512)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('alt_text', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_imag_search__583eac_gin')],
                'constraints': [models.UniqueConstraint(fields=('asset_url',), name='unique_image_asset_url')],
            },
        ),
        migrations.CreateModel(
            name='TextFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_url', models.URLField(blank=True, db_index=True, max_length=1024, null=True)),
                ('source_page_url', models.URLField(db_index=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('content', config='english'), output_field=django.contrib.postgres.search.SearchVectorField())),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_text_search__a21a0a_gin')],
            },
        ),
    ]
