# Generated by Django 5.2.4 on 2025-07-30 11:49

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofeatures',
            name='transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imagefeatures',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('alt_text', config='english'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddField(
            model_name='textfeatures',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('content', config='english'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imagefeatures',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='textfeatures',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='audiofeatures',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('transcript', config='english'), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
    ]
