# Generated by Django 5.2.4 on 2025-07-30 11:50

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_audiofeatures_transcript_imagefeatures_search_vector_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='audiofeatures',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_audi_search__7b4d2c_gin'),
        ),
        migrations.AddIndex(
            model_name='imagefeatures',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_imag_search__583eac_gin'),
        ),
        migrations.AddIndex(
            model_name='textfeatures',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_text_search__a21a0a_gin'),
        ),
    ]
