# Generated by Django 5.2.4 on 2025-08-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_audiofeatures_search_audi_search__7b4d2c_gin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofeatures',
            name='transcript',
        ),
    ]
