# Generated by Django 5.2.4 on 2025-08-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_remove_audiofeatures_transcript'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='audiofeatures',
            name='search_audi_search__7b4d2c_gin',
        ),
    ]
